#!/bin/bash
git add . # tiek pieteikstas adreses "uzmanisanani"
git config --global user.name naraaaaa
git config --global user.email naraaaofficial@gmail.com
#git commit -m "class_05" 
git commit -m "class_$1"
git push origin main
